version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql 
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h ${DB_ADR} -u${DB_USER} -p${DB_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build: .
    image: jiiminhong/plant_be:latest
    container_name: backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    image: jiiminhong/plant_fe:latest
    container_name: frontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}

  nginx:
    image: nginx:latest
    container_name: nginx
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data:
