version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    image: jiiminhong/plant_be:latest
    container_name: backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    image: jiiminhong/plant_fe:latest
    container_name: frontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - REACT_APP_NAVER_CALLBACK_URL=${NAVER_CALLBACK_URL}

  nginx:
    image: nginx:latest
    container_name: nginx
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data:
